# Generated by Django 5.0.2 on 2024-03-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_post_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="teaching_file"),
        ),
    ]
