# Generated by Django 5.0.2 on 2024-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_profile_url_course_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
