# Generated by Django 5.0.2 on 2024-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="default.jpg", upload_to=""),
        ),
    ]
