# Generated by Django 5.0.2 on 2024-03-02 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_profile_pic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="course",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="student",
        ),
        migrations.RemoveField(
            model_name="teacher_request",
            name="teacher_email",
        ),
        migrations.RemoveField(
            model_name="teacher_request",
            name="teacher_profile",
        ),
        migrations.AddField(
            model_name="teacher_request",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
