# Generated by Django 5.0.2 on 2024-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_profile_desc_profile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
